# Import

In [1]:
import pandas as pd 
import numpy as np

In [2]:
data = pd.read_csv('/data/danield2255/music.csv')
data.head()

,artist.hotttnesss,artist.id,artist.name,artist_mbtags,artist_mbtags_count,bars_confidence,bars_start,beats_confidence,beats_start,duration,...,start_of_fade_out,tatums_confidence,tatums_start,tempo,terms,terms_freq,time_signature,time_signature_confidence,title,year
0,0.401998,ARD7TVE1187B99BFB1,Casual,NaN,0.0,0.643,0.58521,0.834,0.58521,218.93179,...,218.932,0.779,0.28519,92.198,hip hop,1.000000,4.0,0.778,I Didn't Mean To,0
1,0.417500,ARMJAGH1187FB546F3,The Box Tops,classic pop and rock,1.0,0.007,0.71054,1.000,0.20627,148.03546,...,137.915,0.969,0.20627,121.274,blue-eyed soul,1.000000,4.0,0.384,Soul Deep,1969
2,0.343428,ARKRRTF1187B9984DA,Sonora Santanera,NaN,0.0,0.980,0.73152,0.980,0.73152,177.47546,...,172.304,0.482,0.42132,100.070,salsa,1.000000,1.0,0.000,Amor De Cabaret,0
3,0.454231,AR7G5I41187FB4CE6C,Adam Ant,uk,1.0,0.017,1.30621,0.809,0.81002,233.40363,...,217.124,0.601,0.56254,119.293,pop rock,0.988584,4.0,0.000,Something Girls,1982
4,0.401724,ARXR32B1187FB57099,Gob,NaN,0.0,0.175,1.06368,0.883,0.13576,209.60608,...,198.699,1.000,0.13576,129.738,pop punk,0.887288,4.0,0.562,Face the Ashes,2007

# Raw Data Description

In [3]:
print(data.shape)
print(data.dtypes)
data.describe(include = 'all')

(10000, 35)
artist.hotttnesss            float64
artist.id                     object
artist.name                   object
artist_mbtags                 object
artist_mbtags_count          float64
bars_confidence              float64
bars_start                   float64
beats_confidence             float64
beats_start                  float64
duration                     float64
end_of_fade_in               float64
familiarity                  float64
key                          float64
key_confidence               float64
latitude                     float64
location                      object
longitude                    float64
loudness                     float64
mode                           int64
mode_confidence              float64
release.id                     int64
release.name                  object
similar                       object
song.hotttnesss              float64
song.id                       object
start_of_fade_out            float64
tatums_confidence            float64
tatums_start                 float64
tempo                        float64
terms                         object
terms_freq                   float64
time_signature               float64
time_signature_confidence    float64
title                         object
year                           int64
dtype: object

,artist.hotttnesss,artist.id,artist.name,artist_mbtags,artist_mbtags_count,bars_confidence,bars_start,beats_confidence,beats_start,duration,...,start_of_fade_out,tatums_confidence,tatums_start,tempo,terms,terms_freq,time_signature,time_signature_confidence,title,year
count,10000.000000,10000,10000,3711,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,...,10000.000000,10000.000000,10000.000000,10000.000000,9995,1.000000e+04,10000.000000,10000.000000,9999,10000.000000
unique,NaN,3888,4412,276,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,458,NaN,NaN,NaN,9708,NaN
top,NaN,AROIHOI122988FEB8E,Mario Rosenstock,classic pop and rock,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,hip hop,NaN,NaN,NaN,Intro,NaN
freq,NaN,13,13,254,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,346,NaN,NaN,NaN,14,NaN
mean,0.385552,NaN,NaN,NaN,0.524686,0.239595,1.065246,0.613963,0.428497,240.622038,...,229.883436,0.507875,0.299886,122.900913,NaN,2.248903e+02,3.564443,0.599785,NaN,934.704600
std,0.143647,NaN,NaN,NaN,0.884095,0.288259,1.723468,0.322441,0.806217,246.084090,...,112.024303,0.332357,0.510925,35.204746,NaN,2.239216e+04,1.266620,8.991567,NaN,996.650657
min,0.000000,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,-60.000000,1.044440,...,-21.394000,0.000000,0.000000,0.000000,NaN,0.000000e+00,0.000000,0.000000,NaN,0.000000
25%,0.325266,NaN,NaN,NaN,0.000000,0.035000,0.441590,0.409750,0.194655,176.032200,...,168.855750,0.237000,0.110692,96.959500,NaN,9.476125e-01,3.000000,0.097750,NaN,0.000000
50%,0.380742,NaN,NaN,NaN,0.000000,0.120000,0.785460,0.686000,0.332585,223.059140,...,213.864500,0.500000,0.191520,120.156500,NaN,9.999728e-01,4.000000,0.551000,NaN,0.000000
75%,0.453858,NaN,NaN,NaN,1.000000,0.351000,1.224075,0.882000,0.500753,276.375060,...,266.274750,0.774250,0.294743,144.006750,NaN,1.000000e+00,4.000000,0.864000,NaN,2000.000000
max,1.082503,NaN,NaN,NaN,9.000000,8.855240,59.743540,1.000000,12.245830,22050.000000,...,1813.426000,9.227560,12.245830,262.828000,NaN,2.239217e+06,7.000000,898.891000,NaN,2010.000000

The initial dataset starts with 10,000 rows and 35 columns.